//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CalculoHoras
    {
        public int Id { get; set; }
        [DisplayName("Dispositivos")]
        public Nullable<int> Id_Servicio_Descripcion { get; set; }
        [DisplayName("Cantidad Servicio")]
        [Range(0, 9999)]
        public Nullable<int> cantidad_Servicio { get; set; }
        [DisplayName("Tipo Operación")]
        public Nullable<int> Id_Tipo_Operacion { get; set; }
        [DisplayName("Requerimientos")]
        public Nullable<int> Id_Volumen_Ticket { get; set; }
        [DisplayName("Cantidad Requerimientos")]
        [Range(0, 9999)]
        public Nullable<int> Cantidad_Volumen_Ticket { get; set; }
        public Nullable<int> Resultado { get; set; }
        [DisplayName("Dispositivos")]
        public Nullable<int> Id_servicio { get; set; }
        public Nullable<int> Id_calculo { get; set; }

        public virtual Servicio_Descripcion Servicio_Descripcion { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual Volumen_Ticket Volumen_Ticket { get; set; }
        public virtual Calculo Calculo { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
