//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculoHoras
    {
        public int Id { get; set; }
        public Nullable<int> Id_Servicio_Descripcion { get; set; }
        public Nullable<int> cantidad_Servicio { get; set; }
        public Nullable<int> Id_Tipo_Operacion { get; set; }
        public Nullable<int> Id_Volumen_Ticket { get; set; }
        public Nullable<int> Cantidad_Volumen_Ticket { get; set; }
        public Nullable<int> Resultado { get; set; }
        public Nullable<int> Id_servicio { get; set; }
        public Nullable<int> Id_calculo { get; set; }
    
        public virtual Servicio_Descripcion Servicio_Descripcion { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual Volumen_Ticket Volumen_Ticket { get; set; }
        public virtual Calculo Calculo { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
