//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculosResultados
    {
        public int IdCalculo { get; set; }
        public Nullable<decimal> resultado { get; set; }
        public Nullable<int> cantidadPersonas { get; set; }
        public Nullable<System.DateTime> fechaCalculo { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTipoInfraestructura { get; set; }
        public Nullable<int> idTipoOperacion { get; set; }
        public Nullable<int> idTipoTicket { get; set; }
        public Nullable<int> idTipoServicioBrindado { get; set; }
        public Nullable<int> idTipoActividadBase { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TipoActividadBase TipoActividadBase { get; set; }
        public virtual TipoInfraestructura TipoInfraestructura { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual TipoServicioBrindado TipoServicioBrindado { get; set; }
        public virtual TipoTicket TipoTicket { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
