//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public Servicios()
        {
            this.Servicio_Descripcion = new HashSet<Servicio_Descripcion>();
        }
    
        public int Id { get; set; }
        public string Decripcion { get; set; }
    
        public virtual ICollection<Servicio_Descripcion> Servicio_Descripcion { get; set; }
    }
}
