//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Servicio_Descripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio_Descripcion()
        {
            this.CalculoHoras = new HashSet<CalculoHoras>();
        }

        public int Id { get; set; }
        [DisplayName("Dispositivos")]
        public Nullable<int> Id_Servicio { get; set; }
        [DisplayName("Nombre")]
        public string Descripcion { get; set; }
        [DisplayName("Descrpción")]
        public string Referencia { get; set; }
        public Nullable<int> HH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalculoHoras> CalculoHoras { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
