//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalculoEntities : DbContext
    {
        public CalculoEntities()
            : base("name=CalculoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CalculoHoras> CalculoHoras { get; set; }
        public virtual DbSet<CalculosResultados> CalculosResultados { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Servicio_Descripcion> Servicio_Descripcion { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<TipoActividadBase> TipoActividadBase { get; set; }
        public virtual DbSet<TipoInfraestructura> TipoInfraestructura { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
        public virtual DbSet<TipoServicioBrindado> TipoServicioBrindado { get; set; }
        public virtual DbSet<TipoTicket> TipoTicket { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Volumen_Ticket> Volumen_Ticket { get; set; }
        public virtual DbSet<Calculo> Calculo { get; set; }
    
        public virtual ObjectResult<SelectCalculos_Result> SelectCalculos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCalculos_Result>("SelectCalculos");
        }
    
        //public virtual ObjectResult<SelectCalculos_Result> SelectCalculo()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCalculos_Result>("SelectCalculo");
        //}
    
        public virtual ObjectResult<SelectCalculos_Result> selectCal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCalculos_Result>("selectCal");
        }
    }
}
