//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalculoEntities : DbContext
    {
        public CalculoEntities()
            : base("name=CalculoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AspNetRoles> AspNetRoles { get; set; }
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<CalculoHoras> CalculoHoras { get; set; }
        public DbSet<CalculosResultados> CalculosResultados { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Servicio_Descripcion> Servicio_Descripcion { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<TipoActividadBase> TipoActividadBase { get; set; }
        public DbSet<TipoInfraestructura> TipoInfraestructura { get; set; }
        public DbSet<TipoOperacion> TipoOperacion { get; set; }
        public DbSet<TipoServicioBrindado> TipoServicioBrindado { get; set; }
        public DbSet<TipoTicket> TipoTicket { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Volumen_Ticket> Volumen_Ticket { get; set; }
    }
}
