//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInfraestructura
    {
        public TipoInfraestructura()
        {
            this.CalculosResultados = new HashSet<CalculosResultados>();
        }
    
        public int idTipoInfraesteructura { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> estado { get; set; }
    
        public virtual ICollection<CalculosResultados> CalculosResultados { get; set; }
    }
}
