//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.CalculosResultados = new HashSet<CalculosResultados>();
        }
    
        public int idTipoUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string correo { get; set; }
        public string nombre { get; set; }
        public string apellidoP { get; set; }
        public string apellidoM { get; set; }
        public string rut { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idPerfil { get; set; }
    
        public virtual ICollection<CalculosResultados> CalculosResultados { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
