//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCalculoweb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Volumen_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volumen_Ticket()
        {
            this.CalculoHoras = new HashSet<CalculoHoras>();
        }
    
        public int Id { get; set; }
        [DisplayName("Descripción")]
        public string Sugerencia { get; set; }
        [DisplayName("Tipo")]
        public string Descripcion { get; set; }
        [DisplayName("Tiempo base de administración")]
        public Nullable<decimal> HH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalculoHoras> CalculoHoras { get; set; }
    }
}
